### PR TITLE
Added Key to toggle Hud (default: h) and config option to save state.

### PR DESCRIPTION
**Pull request by Nick1st**
I did this cause of #46.
I also added a German translation.

### CODE REVIEW

**Comment by legobmw99** [comment]
Thanks for doing this. 

I'll take a look later, it seems like our Java formatters disagree slightly which is making the diff hard to read on mobile. 

If it all looks good I will happy accept the PR, but I think I will set the key to unbound by default to avoid clutter in large packs.

**Comment by Nick1st** [comment]
Not sure about the last commit, but I think it's better to read a boolean each time the overlay is rendered instead of reading a config option.

**Comment by legobmw99** [comment]
I'm not sure it ultimately matters, but you'd need to also update it in the refresh method in AllomancyConfig. 

This may end up being more work than it is worth for a client side only thing. 

Is there any noticeable difference in performance with the caching? If F3 (possibly with the graph) doesn't show any difference I think it would be better to keep simple. The render methods already check several config values and I don't think it's a performance problem

**Comment by Nick1st** [comment]
No, for me it doesn't matter, but I have an high end pc

**Comment by Nick1st** [comment]
I've tested it with my very bad Laptop and it doesn't make any difference.

**Comment by legobmw99** [comment]
I'd say go ahead and revert that last commit then

**Comment by Nick1st** [comment]
Done

**Review by legobmw99 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
